version: '3'
services:
  spring_boot:
    image: harishmedasani/mongo:1.0
    container_name: harish
    ports:
      - "8080:8080"
    networks: 
      - custom_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - custom_network

  networks:
    custom_network:
    driver: bridge
    


